name: test

on:
  push:
    branches: [main, '!flaky-r*', '!insert-mutations', '!track-flaky']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # base:
  #   runs-on: ${{ matrix.os }}-latest
  #   strategy:
  #     matrix:
  #       os: [ubuntu]
  #       environment:
  #         [
  #           test-base-py313
  #         ]
  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  #       with:
  #         persist-credentials: false
  #     - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
  #       with:
  #         environments: ${{ matrix.environment }}
  #     - name: Test NetworkX
  #       run: pixi run -e ${{ matrix.environment }} test-base

  # default:
  #   runs-on: ${{ matrix.os }}-latest
  #   strategy:
  #     matrix:
  #       os: [ubuntu]
  #       environment:
  #         [
  #           test-default-py312,
  #         ]
  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  #       with:
  #         persist-credentials: false
  #     - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
  #       with:
  #         environments: ${{ matrix.environment }}
  #     - name: Test for warnings at import time
  #       run: pixi run -e ${{ matrix.environment }} check-import
  #     - name: Test NetworkX
  #       run: pixi run -e ${{ matrix.environment }} test-default

  #por enquanto vou usar o extra como oficial que roda 10193 passed, 25 skipped (o base roda 8665 passed, 357 skipped e o defaut,  10083 passed, 62 skipped)
  extra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          environments: test-extra-py312
      - name: Test NetworkX (py312)
        run: pixi run -e test-extra-py312 test-default
